
export const pakistanProvinces = [
  "Azad Kashmir",
  "Balochistan",
  "Gilgit-Baltistan",
  "Islamabad Capital Territory",
  "Khyber Pakhtunkhwa",
  "Punjab",
  "Sindh",
];

export const citiesByProvince = {
  "Azad Kashmir": [
    "Bagh",
    "Bhimber",
    "Hajira",
    "Kotli",
    "Mirpur",
    "Muzaffarabad",
    "Pallandri",
    "Rawalakot",
  ],
  "Balochistan": [
    "Awaran",
    "Barkhan",
    "Chagai",
    "Chaman",
    "Dalbandin",
    "Dera Bugti",
    "Dera Murad Jamali",
    "Duki",
    "Gaddani",
    "Gandava",
    "Gwadar",
    "Harnai",
    "Hub",
    "Jhal Magsi",
    "Jiwani",
    "Kacchi",
    "Kalat",
    "Kech",
    "Kharan",
    "Khuzdar",
    "Killa Abdullah",
    "Killa Saifullah",
    "Kohlu",
    "Lasbela",
    "Loralai",
    "Mastung",
    "Musakhel",
    "Nasirabad",
    "Nushki",
    "Ormara",
    "Panjgur",
    "Pasni",
    "Pishin",
    "Quetta",
    "Sherani",
    "Sibi",
    "Turbat",
    "Uthal",
    "Washuk",
    "Zhob",
    "Ziarat",
  ],
  "Gilgit-Baltistan": [
    "Astore",
    "Chilas",
    "Danyore",
    "Gahkuch",
    "Ghanche",
    "Ghizer",
    "Gilgit",
    "Hunza",
    "Juglot",
    "Karimabad",
    "Nagar",
    "Skardu",
  ],
  "Islamabad Capital Territory": [
    "Islamabad"
  ],
  "Khyber Pakhtunkhwa": [
    "Abbottabad",
    "Alpuri",
    "Bannu",
    "Batagram",
    "Buner",
    "Charsadda",
    "Chitral",
    "Dera Ismail Khan",
    "Dir",
    "Hangu",
    "Haripur",
    "Karak",
    "Kohat",
    "Lakki Marwat",
    "Lower Dir",
    "Malakand",
    "Mansehra",
    "Mardan",
    "Nowshera",
    "Peshawar",
    "Shangla",
    "Swabi",
    "Swat",
    "Tank",
    "Timargara",
    "Tor Ghar",
    "Upper Dir",
  ],
  "Punjab": [
    "Ahmedpur East",
    "Arifwala",
    "Attock",
    "Bahawalnagar",
    "Bahawalpur",
    "Bhakkar",
    "Bhalwal",
    "Chakwal",
    "Chiniot",
    "Chishtian",
    "Daska",
    "Dera Ghazi Khan",
    "Faisalabad",
    "Gojra",
    "Gujranwala",
    "Gujrat",
    "Hafizabad",
    "Jaranwala",
    "Jhang",
    "Jhelum",
    "Kamalia",
    "Kamoke",
    "Kasur",
    "Khanewal",
    "Khanpur",
    "Khushab",
    "Kot Addu",
    "Lahore",
    "Layyah",
    "Lodhran",
    "Mandi Bahauddin",
    "Mianwali",
    "Multan",
    "Muridke",
    "Muzaffargarh",
    "Narowal",
    "Okara",
    "Pakpattan",
    "Rahim Yar Khan",
    "Rajanpur",
    "Rawalpindi",
    "Sadiqabad",
    "Sahiwal",
    "Sambrial",
    "Sargodha",
    "Sheikhupura",
    "Sialkot",
    "Taxila",
    "Toba Tek Singh",
    "Vehari",
    "Wah Cantonment",
    "Wazirabad",
  ],
  "Sindh": [
    "Badin",
    "Dadu",
    "Ghotki",
    "Hyderabad",
    "Jacobabad",
    "Jamshoro",
    "Karachi",
    "Kashmore",
    "Khairpur",
    "Larkana",
    "Matiari",
    "Mirpur Khas",
    "Naushahro Feroze",
    "Qambar Shahdadkot",
    "Sanghar",
    "Shaheed Benazirabad",
    "Shikarpur",
    "Sujawal",
    "Sukkur",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Tharparkar",
    "Thatta",
    "Umerkot",
  ]
};
